/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/rishabh/localization/src/localization/msg/lp.msg
 *
 */


#ifndef LOCALIZATION_MESSAGE_LP_H
#define LOCALIZATION_MESSAGE_LP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localization
{
template <class ContainerAllocator>
struct lp_
{
  typedef lp_<ContainerAllocator> Type;

  lp_()
    : stamp()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , av_x(0.0)
    , av_y(0.0)
    , av_z(0.0)  {
    }
  lp_(const ContainerAllocator& _alloc)
    : stamp()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , av_x(0.0)
    , av_y(0.0)
    , av_z(0.0)  {
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _av_x_type;
  _av_x_type av_x;

   typedef double _av_y_type;
  _av_y_type av_y;

   typedef double _av_z_type;
  _av_z_type av_z;




  typedef boost::shared_ptr< ::localization::lp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::lp_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct lp_

typedef ::localization::lp_<std::allocator<void> > lp;

typedef boost::shared_ptr< ::localization::lp > lpPtr;
typedef boost::shared_ptr< ::localization::lp const> lpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::lp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::lp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/hydro/share/nav_msgs/cmake/../msg'], 'geographic_msgs': ['/opt/ros/hydro/share/geographic_msgs/cmake/../msg'], 'localization': ['/home/rishabh/localization/src/localization/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/hydro/share/uuid_msgs/cmake/../msg'], 'tf': ['/opt/ros/hydro/share/tf/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localization::lp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::lp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::lp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::lp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::lp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::lp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::lp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7853bfeaafcda21444d83e284585ef8";
  }

  static const char* value(const ::localization::lp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7853bfeaafcda21ULL;
  static const uint64_t static_value2 = 0x444d83e284585ef8ULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::lp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/lp";
  }

  static const char* value(const ::localization::lp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::lp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# For the info to be sent in and around for the low pass filter\n\
\n\
time stamp\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 av_x\n\
float64 av_y\n\
float64 av_z\n\
";
  }

  static const char* value(const ::localization::lp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::lp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.av_x);
      stream.next(m.av_y);
      stream.next(m.av_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct lp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::lp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::lp_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "av_x: ";
    Printer<double>::stream(s, indent + "  ", v.av_x);
    s << indent << "av_y: ";
    Printer<double>::stream(s, indent + "  ", v.av_y);
    s << indent << "av_z: ";
    Printer<double>::stream(s, indent + "  ", v.av_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_LP_H
